-- generated by migrate/build.mjs — do not edit by hand

DROP TABLE IF EXISTS color_categories;
CREATE TABLE color_categories (
  "id" INTEGER PRIMARY KEY,
  "show_in_stock" TEXT,
  "show_in_panel" TEXT,
  "sort_order" INTEGER,
  "created_at" TEXT,
  "updated_at" TEXT
);

DROP TABLE IF EXISTS color_category_translations;
CREATE TABLE color_category_translations (
  "id" INTEGER PRIMARY KEY,
  "color_category_id" INTEGER,
  "language" TEXT,
  "name" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

DROP TABLE IF EXISTS colors;
CREATE TABLE colors (
  "id" INTEGER PRIMARY KEY,
  "color_code" TEXT,
  "thumbnail" TEXT,
  "color_hex" TEXT,
  "color_category_id" INTEGER,
  "price" REAL,
  "sort_order" INTEGER,
  "is_shown" INTEGER,
  "created_at" TEXT,
  "updated_at" TEXT
);

DROP TABLE IF EXISTS doors;
CREATE TABLE doors (
  "id" INTEGER PRIMARY KEY,
  "model_code" TEXT,
  "thumbnail" TEXT,
  "color_id" INTEGER,
  "decorative_glass_name" TEXT,
  "side_glass_code" TEXT,
  "second_panel_color_id" INTEGER,
  "has_glass" INTEGER,
  "price" REAL,
  "sort_order" INTEGER,
  "is_shown" INTEGER,
  "created_at" TEXT,
  "updated_at" TEXT,
  "is_default" INTEGER
);

DROP TABLE IF EXISTS dmodels;
CREATE TABLE dmodels (
  "id" INTEGER PRIMARY KEY,
  "dmodel_name" TEXT,
  "suffix" TEXT
);

DROP TABLE IF EXISTS dmodel_door;
CREATE TABLE dmodel_door (
  "id" INTEGER PRIMARY KEY,
  "dmodel_id" INTEGER,
  "door_id" INTEGER
);

DROP TABLE IF EXISTS equipment_glasses;
CREATE TABLE equipment_glasses (
  "id" INTEGER PRIMARY KEY,
  "type" TEXT,
  "thumbnail" TEXT,
  "price" REAL,
  "sort_order" INTEGER,
  "is_shown" INTEGER,
  "created_at" TEXT,
  "updated_at" TEXT,
  "is_default" INTEGER
);

DROP TABLE IF EXISTS equipment_glass_translations;
CREATE TABLE equipment_glass_translations (
  "id" INTEGER PRIMARY KEY,
  "glass_id" INTEGER,
  "language" TEXT,
  "name" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

DROP TABLE IF EXISTS equipment_locks;
CREATE TABLE equipment_locks (
  "id" INTEGER PRIMARY KEY,
  "thumbnail" TEXT,
  "price" REAL,
  "sort_order" INTEGER,
  "code" TEXT,
  "is_shown" INTEGER,
  "created_at" TEXT,
  "updated_at" TEXT,
  "is_default" INTEGER
);

DROP TABLE IF EXISTS equipment_lock_translations;
CREATE TABLE equipment_lock_translations (
  "id" INTEGER PRIMARY KEY,
  "lock_id" INTEGER,
  "language" TEXT,
  "name" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

DROP TABLE IF EXISTS equipment_systems;
CREATE TABLE equipment_systems (
  "id" INTEGER PRIMARY KEY,
  "name" TEXT,
  "code" TEXT,
  "thumbnail" TEXT,
  "price" REAL,
  "sort_order" INTEGER,
  "is_shown" INTEGER,
  "created_at" TEXT,
  "updated_at" TEXT,
  "is_default" INTEGER
);

DROP TABLE IF EXISTS equipment_system_translations;
CREATE TABLE equipment_system_translations (
  "id" INTEGER PRIMARY KEY,
  "equipment_id" INTEGER,
  "language" TEXT,
  "description" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

DROP TABLE IF EXISTS equipment_other_categories;
CREATE TABLE equipment_other_categories (
  "id" INTEGER PRIMARY KEY,
  "name" TEXT
);

DROP TABLE IF EXISTS equipment_others;
CREATE TABLE equipment_others (
  "id" INTEGER PRIMARY KEY,
  "code" TEXT,
  "thumbnail" TEXT,
  "image" TEXT,
  "inner_image" TEXT,
  "price" REAL,
  "sort_order" INTEGER,
  "is_shown" INTEGER,
  "category_id" INTEGER,
  "subcategory" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "is_subcategory" INTEGER,
  "is_default" INTEGER
);

DROP TABLE IF EXISTS equipment_other_translations;
CREATE TABLE equipment_other_translations (
  "id" INTEGER PRIMARY KEY,
  "equipment_id" INTEGER,
  "language" TEXT,
  "name" TEXT,
  "description" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

DROP TABLE IF EXISTS house_colors;
CREATE TABLE house_colors (
  "id" INTEGER PRIMARY KEY,
  "color_code" TEXT,
  "color_hex" TEXT,
  "margin_color_hex" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "thumbnail" TEXT
);

DROP TABLE IF EXISTS houses;
CREATE TABLE houses (
  "id" INTEGER PRIMARY KEY,
  "image" TEXT
);

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  "id" INTEGER PRIMARY KEY,
  "company_name" TEXT,
  "city" TEXT,
  "zip_code" TEXT,
  "address" TEXT,
  "pib" TEXT,
  "social_number" INTEGER,
  "giro_account" TEXT,
  "phone" TEXT,
  "mobile_phone" TEXT,
  "email" TEXT,
  "contact_person" TEXT,
  "currency" TEXT,
  "username" TEXT,
  "password" TEXT,
  "logo" TEXT,
  "role" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

DROP TABLE IF EXISTS markups;
CREATE TABLE markups (
  "id" INTEGER PRIMARY KEY,
  "user_id" INTEGER,
  "markup_label" TEXT,
  "markup_value" REAL,
  "default" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

