// Turn the exported Laravel catalog (migrate/data/*.json) into:
//   migrate/out/schema.sql   — clean D1 schema
//   migrate/out/seed.sql     — INSERTs with clean R2 paths
//   migrate/out/manifest.tsv — old-path <TAB> new-R2-key  (drives the asset upload)
import fs from "fs";

const DATA = "migrate/data";
const OUT = "migrate/out";
fs.mkdirSync(OUT, { recursive: true });
const read = (t) => JSON.parse(fs.readFileSync(`${DATA}/${t}.json`, "utf8"));

// equipment_other category id -> code (canonical FE codes)
const CATMAP = {
  1: "handrail", 2: "doorknobInside", 3: "rosette", 4: "parapetProtection",
  5: "accessControl", 6: "spy", 7: "cylinder", 8: "hinges",
  9: "electromagneticReceiver", 10: "automaticClosingDevice", 11: "houseNumbers",
};
const catCode = (id) => CATMAP[id] || `cat${id}`;

// which columns hold asset paths, and the clean key each maps to
const PATH_COLS = {
  doors: { thumbnail: (r) => `doors/${r.model_code}/thumbnail.png` },
  colors: { thumbnail: (r) => `colors/${r.id}.png` },
  equipment_glasses: { thumbnail: (r) => `glasses/${r.id}.png` },
  equipment_locks: { thumbnail: (r) => `locks/${r.id}.png` },
  equipment_systems: { thumbnail: (r) => `systems/${r.id}.png` },
  equipment_others: {
    image: (r) => `equipment/${catCode(r.category_id)}/${r.id}.png`,
    inner_image: (r) => `equipment/${catCode(r.category_id)}/${r.id}-inner.png`,
    thumbnail: (r) => `equipment/${catCode(r.category_id)}/${r.id}-thumb.png`,
  },
  house_colors: { thumbnail: (r) => `house-colors/${r.id}.png` },
  houses: { image: (r) => `houses/${r.id}.png` },
  users: { logo: (r) => `logos/${r.id}.png` },
};

const sqlType = (col) => {
  if (col === "id") return "INTEGER PRIMARY KEY";
  if (/(^id$|_id$|^is_|_number$|sort_order|category_id|has_glass|is_default|is_shown)/.test(col)) return "INTEGER";
  if (col === "price" || /(width|height|markup_value|offset_)/.test(col)) return "REAL";
  return "TEXT";
};

const q = (id) => `"${id}"`;
function sqlVal(v) {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "1" : "0";
  return `'${String(v).replace(/'/g, "''")}'`;
}

const TABLES = [
  "color_categories", "color_category_translations", "colors", "doors",
  "dmodels", "dmodel_door",
  "equipment_glasses", "equipment_glass_translations",
  "equipment_locks", "equipment_lock_translations",
  "equipment_systems", "equipment_system_translations",
  "equipment_other_categories", "equipment_others", "equipment_other_translations",
  "house_colors", "houses", "users", "markups",
];

let schema = "-- generated by migrate/build.mjs — do not edit by hand\n\n";
let seed = "-- generated by migrate/build.mjs\n\n";
let manifest = "";
const stats = {};

for (const t of TABLES) {
  let rows;
  try { rows = read(t); } catch { console.warn("skip (no dump):", t); continue; }
  if (!rows.length) { console.warn("empty:", t); continue; }
  const cols = Object.keys(rows[0]);

  schema += `DROP TABLE IF EXISTS ${t};\nCREATE TABLE ${t} (\n  ` +
    cols.map((c) => `${q(c)} ${sqlType(c)}`).join(",\n  ") + `\n);\n\n`;

  const pmap = PATH_COLS[t] || {};
  let mapped = 0;
  for (const row of rows) {
    const vals = cols.map((c) => {
      let v = row[c];
      if (pmap[c] && v != null && String(v).length) {
        const nk = pmap[c](row);
        manifest += `${v}\t${nk}\n`;
        v = nk;
        mapped++;
      }
      return sqlVal(v);
    });
    seed += `INSERT INTO ${t} (${cols.map(q).join(", ")}) VALUES (${vals.join(", ")});\n`;
  }
  stats[t] = { rows: rows.length, pathsMapped: mapped };
}

// door part-assets (not in DB) migrate whole-folder: images/doors/{code}/* -> doors/{code}/*
manifest += "# DIR images/doors/* -> doors/*\n# DIR images/frame/* -> frame/*\n# DIR images/glass/* -> glass/*\n# DIR images/sideglass/* -> sideglass/*\n";

fs.writeFileSync(`${OUT}/schema.sql`, schema);
fs.writeFileSync(`${OUT}/seed.sql`, seed);
fs.writeFileSync(`${OUT}/manifest.tsv`, manifest);
console.table(stats);
console.log(`schema: ${schema.split("CREATE TABLE").length - 1} tables | seed: ${seed.split("INSERT").length - 1} inserts | manifest: ${manifest.split("\n").filter((l) => l.includes("\t")).length} files`);
